---
- name: Setup an IPAserver
  hosts: all
  become: yes

  pre_tasks:
    - include_vars: vars.yml

    - name: Test connection
      ping:

    - name: Register with subscription-manager
      redhat_subscription:
        state: present
        username: "{{ subscription_username }}"
        password: "{{ subscription_password }}"
        auto_attach: true
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts
        ['distribution_major_version'] == '8'
      ignore_errors: yes

  collections:
   - freeipa.ansible_freeipa

  tasks:
    - name: import role from a collection
      import_role:
        name: freeipa.ansible_freeipa.ipaserver
